before:
  hooks:
    - go mod download
builds:
- main: ./cmd/server/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
release:
  github:
  prerelease: auto
